title: Q. Serrano
email: qode66@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "Programamos ideas, cultivamos innovaci√≥n. Prototipamos lo imposible"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: qserrano
github_username:  qserrano

#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num"

markdown: kramdown
author:
  name: Q. Serrano
  email: qode66@gmail.com

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

permalink: pretty
keep_files:
  - .git
  - .svn
